<?php
/**
 * Functions that must be loaded early in the initialization.
 * @since 1.3.9-beta
 *
 * @package ReallySimpleCMS
 *
 * ## AUTOLOADERS [1] ##
 * - spl_autoload_register(string $class) [class autoloader]
 *
 * ## GLOBAL VARS [5] ##
 * - null|object $rs_query
 * - array $rs_session
 * - object $rs_register
 * - array $rs_error
 * - null|string $rs_theme_path
 *
 * ## FUNCTIONS [17] ##
 * { FILES [4] }
 * - requireFile(string $filepath, bool $once): void
 * - includeFile(string $filepath, bool $once): void
 * - requireFiles(array $filepaths, bool $once): void
 * - includeFiles(array $filepaths, bool $once): void
 * { SYSTEM SETUP [5] }
 * - baseSetup(): void
 * - themeSetup(): void
 * - checkPHPVersion(): void
 * - checkDBConfig(): void
 * - checkDBStatus(): void
 * { MISCELLANEOUS [8] }
 * - isAdmin(): bool
 * - isDebugMode(): bool
 * - isSecureConnection(): bool
 * - redirect(string $url, int $status): void
 * - getClassFilename(string $name): string
 * - formatPathFragment(string $frag): string
 * - unslash(string $text): string
 * - slash(string $text): string
 */

require_once PATH . INC . '/polyfill-functions.php';

/*------------------------------------*\
    AUTOLOADERS
	 (must be placed before any
	 class declarations)
\*------------------------------------*/

/**
 * Autoload a class.
 * @since 1.0.2-alpha
 *
 * @param string $class -- The name of the class.
 */
spl_autoload_register(function(string $class) {
	$file = PATH . INC . getClassFilename($class);
	
	if(isset($file) && file_exists($file)) require $file;
});

/*------------------------------------*\
    GLOBAL VARIABLES
\*------------------------------------*/

/**
 * Database query connection.
 * @since 1.0.0-alpha
 *
 * @var null|object
 */
$rs_query = null;

/**
 * User session data.
 * @since 2.0.1-alpha
 *
 * @var array
 */
$rs_session = array();

/**
 * Registry handler.
 * @since 1.3.15-beta
 *
 * @var object
 */
$rs_register = new \Engine\Register;

/**
 * PHP-specific errors that are generated by the system.
 * @since 1.3.14-beta
 *
 * @var object
 */
$rs_error = new \Engine\ErrorHandler;

/**
 * The path to the active theme.
 * @since 1.3.15-beta
 *
 * @var null|string
 */
$rs_theme_path = null;

/*------------------------------------*\
    FILES
\*------------------------------------*/

/**
 * Require a file.
 * @since 1.3.14-beta
 *
 * @param string $filepath -- The path to the file.
 * @param bool $once (optional) -- Whether to only require the file once.
 */
function requireFile(string $filepath, bool $once = true): void {
	// Active superglobals must be included here
	global $rs_query, $rs_session, $rs_register, $rs_error, $rs_theme_path;
	
	try {
		if($once === true)
			@require_once $filepath;
		else
			@require $filepath;
	} catch(\Throwable $e) {
		$rs_error->logError($e);
		
		if(isDebugMode())
			$rs_error->triggerError();
	}
}

/**
 * Include a file.
 * @since 1.3.14-beta
 *
 * @param string $filepath -- The path to the file.
 * @param bool $once (optional) -- Whether to only include the file once.
 */
function includeFile(string $filepath, bool $once = true): void {
	// Active superglobals must be included here
	global $rs_query, $rs_session, $rs_register, $rs_error, $rs_theme_path;
	
	try {
		if($once === true)
			@include_once $filepath;
		else
			@include $filepath;
	} catch(\Throwable $e) {
		$rs_error->logError($e);
		
		if(isDebugMode())
			$rs_error->triggerError();
	}
}

/**
 * Require multiple files.
 * @since 1.3.14-beta
 *
 * @param array $filepaths -- The paths to the files.
 * @param bool $once (optional) -- Whether to only require the files once.
 */
function requireFiles(array $filepaths, bool $once = true): void {
	foreach($filepaths as $filepath) requireFile($filepath, $once);
}

/**
 * Include multiple files.
 * @since 1.3.14-beta
 *
 * @param array $filepaths -- The paths to the files.
 * @param bool $once (optional) -- Whether to only include the files once.
 */
function includeFiles(array $filepaths, bool $once = true): void {
	foreach($filepaths as $filepath) includeFile($filepath, $once);
}

/*------------------------------------*\
    SYSTEM SETUP
\*------------------------------------*/

/**
 * Conduct basic system setup.
 * Can be run from any file that is accessed directly, such as an AJAX loader.
 * @since 1.3.14-beta
 */
function baseSetup(): void {
	global $rs_query, $rs_session;
	
	/**
	 * ## PHASE 1 ##
	 * Initial checks/database config setup
	 */
	
	checkPHPVersion();
	
	if(!file_exists(RS_CONFIG)) redirect(SETUP . '/rsdb-config.php');
	
	requireFiles(array(RS_CONFIG, RS_DEBUG_FUNC, GLOBAL_FUNC));
	
	checkContentDir();
	
	/**
	 * ## PHASE 2 ##
	 * Database connection/initialization
	 */
	
	$rs_query = new \Engine\Query;
	checkDBStatus();
	
	/**
	 * ## PHASE 3 ##
	 * Database installation
	 */
	
	requireFile(RS_SCHEMA);
	
	$schema = dbSchema();
	$tables = $rs_query->showTables();
	
	if(empty($tables)) redirect(SETUP . '/rsdb-install.php');
	
	// Verify all required tables exist
	// For a list, see `schema.php`
	foreach($schema as $key => $value) {
		if(!$rs_query->tableExists($key)) {
			$rs_query->createTable($key, $value);
			# populateTable($key);
		}
	}
	
	/**
	 * ## PHASE 4 ##
	 * Login status/registries/software update checks
	 */
	
	if(isset($_COOKIE['session']) && isValidSession($_COOKIE['session']))
		$rs_session = getOnlineUser($_COOKIE['session']);
	
	registerDefaultPostTypes();
	registerDefaultTaxonomies();
	# registerRequiredModules();
	registerThemes();
	registerAdminThemes();
	
	// Maintenance mode, triggered by defining `MAINT_MODE` in `config.php`
	if((defined('MAINT_MODE') && MAINT_MODE === true) && (!isLogin() && !is404()) && !isset($rs_session))
		requireFile(PATH . INC . '/maintenance.php');
	
	// An update is running; triggered by the update system
	#if(isset($rs_doing_upgrade) && $rs_doing_upgrade === true)
	if(!defined('BASE_INIT') || (defined('BASE_INIT') && BASE_INIT === false) && isset($rs_session))
		requireFile(PATH . INC . '/update.php');
}

/**
 * Conduct theme setup.
 * Can be run from any file that is accessed directly, such as an AJAX loader.
 * Theme initialization does not run if `BASE_INIT` is defined and true.
 * @since 1.3.15-beta
 */
function themeSetup(): void {
	
	/**
	 * ## PHASE 1 ##
	 * Initialize functions and theme files
	 */
	
	// Check whether only the base files and functions should be initialized
	if(!defined('BASE_INIT') || (defined('BASE_INIT') && BASE_INIT === false)) {
		requireFile(RS_FUNC);
		
		if(isLogin()) {
			// We're logging in
			handleSecureLogin();
		} elseif(!isAdmin() && !is404()) {
			requireFiles(array(
				PATH . INC . '/theme-functions.php', // Theme-specific functions
				PATH . INC . '/load-theme.php' // Initialize the theme
			));
			
			// Determine the type of page being viewed (e.g., post, term, etc.)
			// This must fire AFTER theme loads to include custom post types, taxonomies, etc.
			guessPageType();
			
			requireFiles(array(
				PATH . INC . '/sitemap-index.php', // Sitemap loader
				PATH . INC . '/load-template.php' // Template loader
			));
		}
	}
}

/**
 * Make sure the server is running the required PHP version.
 * @since 1.3.9-beta
 */
function checkPHPVersion(): void {
	$notice = 'The minimum version of PHP that is supported by ' . RS_ENGINE . ' is ' . PHP_MINIMUM . '; your server is running on ' . PHP_VERSION . '. Please upgrade to the minimum required version or higher to use this software.';
	
	if(version_compare(PHP_VERSION, PHP_MINIMUM, '<'))
		exit('<p>' . $notice . '</p>');
}

/**
 * Make sure a database config file doesn't already exist.
 * @since 1.3.14-beta
 */
function checkDBConfig(): void {
	$notice = 'A configuration file already exists. If you wish to continue setup, please delete the existing file.';
	
	if(file_exists(RS_CONFIG))
		exit('<p>' . $notice . '</p>');
}

/**
 * Make sure the database can be connected to.
 * @since 1.0.0-alpha
 */
function checkDBStatus(): void {
	global $rs_query;
	
	$notice = 'There is a problem with your database connection. Check your <code>config.php</code> file located in the <code>root</code> directory of your installation.';
	
	if(!$rs_query->conn_status)
		exit('<p>' . $notice . '</p>');
}

/*------------------------------------*\
    MISCELLANEOUS
\*------------------------------------*/

/**
 * Check whether the user is viewing a page on the admin dashboard.
 * @since 1.0.6-beta
 *
 * @return bool
 */
function isAdmin(): bool {
	return str_starts_with($_SERVER['REQUEST_URI'], '/admin/');
}

/**
 * Check whether the system is in debug mode.
 * @since 1.3.14-beta
 *
 * @return bool
 */
function isDebugMode(): bool {
	return defined('DEBUG_MODE') && DEBUG_MODE === true;
}

/**
 * Check whether the site is using an SSL certificate.
 * @since 1.3.14-beta
 *
 * @return bool
 */
function isSecureConnection(): bool {
	return !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on';
}

/**
 * Redirect to a specified URL.
 * @since 1.7.2-alpha
 *
 * @param string $url -- The URL to redirect to.
 * @param int $status (optional) -- The HTTP status code.
 */
function redirect(string $url, int $status = 302): void {
	header('Location: ' . $url, true, $status);
	exit;
}

/**
 * Construct a class' filename.
 * @since 1.3.9-beta
 *
 * @param string $name -- The name of the class.
 * @return string
 */
function getClassFilename(string $name): string {
	$is_enum = $is_interface = false;
	
	$name = str_replace('\\', '/', $name);
	$path = array();
	
	if(str_contains($name, '/')) {
		$raw_path = explode('/', $name);
		$name = array_pop($raw_path);
		
		foreach($raw_path as $p)
			$path[] = formatPathFragment($p);
	}
	
	// Enums
	if(in_array('enums', $path, true))
		$is_enum = true;
	
	// Interfaces
	if(str_ends_with($name, 'Interface')) {
		$is_interface = true;
		$name = substr($name, 0, strpos($name, 'Interface'));
	}
	
	$name = formatPathFragment($name);
	$path = slash(implode('/', $path));
	$path = !str_starts_with($path, '/') ? '/' . $path : $path;
	
	// Set prefix
	if($is_enum)
		$px = 'enum-';
	elseif($is_interface)
		$px = 'interface-';
	else
		$px = 'class-';
	
	return $path . $px . $name . '.php';
}

/**
 * Format a fragment of a file path.
 * @since 1.3.9-beta
 *
 * @param string $frag -- The file path fragment.
 * @return string
 */
function formatPathFragment(string $frag): string {
	preg_match_all('/[A-Z][a-z]+/', $frag, $matches, PREG_SET_ORDER);
	
	if(count($matches) > 1) {
		$first_match = implode('', array_shift($matches));
		$m_string = '';
		
		foreach($matches as $match)
			$m_string .= '-' . implode('', $match);
		
		$frag = $first_match . $m_string;
	}
	
	return strtolower($frag);
}

/**
 * Remove a trailing slash from a string.
 * @since 1.3.6-beta
 *
 * @param string $text -- The text string.
 * @return string
 */
function unslash(string $text): string {
	return rtrim($text, '/\\');
}

/**
 * Add a trailing slash to a string.
 * @since 1.3.6-beta
 *
 * @param string $text -- The text string.
 * @return string
 */
function slash(string $text): string {
	return unslash($text) . '/';
}